### ISSUE TITLE
George's Paper

### ISSUE THREAD

**Issue by gbreynol** [tinoreskovic/Mass-Media-Independent-Research#24]

**Comment by gbreynol** [comment]
https://docs.google.com/document/d/1Tav6sMWNMi57076I4YP6GIQBRY2QCrdAuq4DpMNmVEo/edit

**Comment by jmshapir** [comment]
just a note that i have seen this and will hopefully send comments soon

**Comment by jmshapir** [comment]
[george.pdf](https://github.com/tinoreskovic/Mass-Media-Independent-Research/files/977367/george.pdf)
@gbreynol here you go! A bunch of these relate to "look and feel" issues. You should probably revisit some of the published articles we saw in class (e.g. Di Tella & Franceschelli) for ideas on formatting regression tables, plots, etc.

@awjiang @tinoreskovic @lilyhoffman17 @gbreynol @msanwalk hope everyone's edits are going well and that you are reading and commenting on each other's papers!

**Comment by msanwalk** [comment]
Hi George - some edits and thoughts for you!
[C4ToYourDoor.pdf](https://github.com/tinoreskovic/Mass-Media-Independent-Research/files/983683/C4ToYourDoor.pdf)
