### ISSUE TITLE
Updates to the background section of draft

### ISSUE THREAD

**Issue by lilyhoffman17** [tinoreskovic/Mass-Media-Independent-Research#25]
https://docs.google.com/document/d/1mE2vNAbDbWOoxGLOSnY3Pl0oBzl1sGGmhot6hHLXwIE/edit

** need to make the footnotes more official

**Comment by jmshapir** [comment]
just a note that i have seen this and will hopefully send comments soon

**Comment by jmshapir** [comment]
[lily.pdf](https://github.com/tinoreskovic/Mass-Media-Independent-Research/files/977900/lily.pdf)
@lilyhoffman17 here you go. I commented on intro and background. Let me know if you think there are other parts I could productively review.

**Comment by lilyhoffman17** [comment]
great-will take a look and make edits. thanks for the comments!
