### ISSUE TITLE
Home stretch

### ISSUE THREAD

**Issue by jmshapir** [tinoreskovic/Mass-Media-Independent-Research#27]
![plan](https://cloud.githubusercontent.com/assets/7840353/25821576/b16b8326-3403-11e7-8ca1-068ba70e3d34.jpg)

@awjiang @tinoreskovic @lilyhoffman17 @gbreynol @msanwalk fyi

**Comment by msanwalk** [comment]
Current progress level: 
For paper edits: Incorporated Andrew's detailed comments (thanks Andrew!) and George and Jesse's comments as well. 
For submission: Made JMCQ account, edited word count for abstract, saved figures as individual files to upload, as well as abstract.

To do: (i) Change the voice to third - person (ii) In-text citations (APA style) (iii) save as perfectly formatted word-doc (iv) proof read (v) submit!

Current plan: Should submit by Thursday 18th

**Comment by jmshapir** [comment]
@msanwalk sounds like a plan!

**Comment by jmshapir** [comment]
Notes from today's meeting:
* Andrew plans to submit by Tuesday
* Tin plans to submit by Saturday
* George has sent Jesse a revised draft to read
* Lily will send revised draft Friday that could be submitted to journal (but may be missing some data updates)

**Comment by jmshapir** [comment]
@awjiang @tinoreskovic @lilyhoffman17 @gbreynol @msanwalk can everyone post their status here? My sense on Monday was that most papers should be submitted by now. Thanks!

**Comment by jmshapir** [comment]
@awjiang @tinoreskovic @lilyhoffman17 @gbreynol @msanwalk I thought we were due for an update. Here is what I know:
* @awjiang got a rejection (with some helpful comments) from JLE. I suggest trying again with [Public Choice](https://link.springer.com/journal/11127).
* @lilyhoffman17 is still working on her paper and has added a bunch of new data and analysis.
* @tinoreskovic got an R&R from the JSE and is planning to do the revisions over break and resubmit.

What about @gbreynol and @msanwalk ?

**Comment by gbreynol** [comment]
@jmshapir Sorry for the delayed response (I'm not the best at checking my personal email). Unfortunately, my paper was rejected, and feedback was not very helpful. I'm thinking about going back to it and seeing what improvements I can make.

**Comment by jmshapir** [comment]
No worries @gbreynol. If you want you can forward me the reply from the journal. Maybe I can suggest a direction forward.
