### ISSUE TITLE
Notes on George's Paper (from George)

### ISSUE THREAD

**Issue by gbreynol** [tinoreskovic/Mass-Media-Independent-Research#28]
1) I believe I fixed my NCVS issue, but the magnitudes of effects are still much larger than those found from UCR analysis. I offer several explanations as to why this would happen in the paper. In your notes you suggest that I divide my data by three to keep things on the monthly level. My concern with doing this is that this would underestimate any effects of lyrics. For example, if there were 15 violent victimizations per 100,000 in a quarter, and I divided by three this would estimate 5 per month. But it is possible that that the true values per month were actually 1, 5, 9. Given that I believe there is not an effect, aren’t I better off avoiding underestimating any effect the lyrics could have? Or am I off-base in this thinking?
2) I asked my friends about looking into my songs, but as of now they are all busy with exams and do not have the time. Depending on how vital you think this is, I can delay submission for a few days if you’d like.
3) Because I was fixing my MSA-level analysis, I have not properly formatted my citations yet. I figured it was better to get the latest version of my paper to you sooner and figure them out while you read through it again.

**Comment by jmshapir** [comment]
@gbreynol 
1. Rescaling in this way is common--for example, quarterly GDP data are often rescaled to "annualized" values to make comparisons easier. So I wouldn't worry about that.
2. I think it is worth a bit of delay.
3. OK.
Can you re-post the link to the paper here so that I can make another round of comments?

**Comment by gbreynol** [comment]
https://docs.google.com/document/d/1Tav6sMWNMi57076I4YP6GIQBRY2QCrdAuq4DpMNmVEo/edit

**Comment by gbreynol** [comment]
Results and citations have been updated, and the link should show the newest version.

**Comment by jmshapir** [comment]
@gbreynol see my comments embedded.

The main thing I'd like to see at this point is a little more data validation to make sure the magnitudes you're getting from the UCR and NCVS match up with other published studies or reports.

@tinoreskovic @msanwalk @awjiang @lilyhoffman17 if anyone has time it would be great if you can help @gbreynol look into this.

**Comment by gbreynol** [comment]
I believe I made all edits. A couple of things:
1. I changed the NCVS rate to the one used by BJS. This, along with fixing an error I found in my code, led to much smaller magnitudes on coefficients. They are comparable to other coefficients found in other studies done with the data, one of which I reference in the results section of the paper.
2. When I opened the paper as a pdf I did not have the same issues with the visuals of the tables that you did. I'm not sure how to proceed.

**Comment by jmshapir** [comment]
@gbreynol:
1. That sounds good. In addition to comparing to other coefficients I would just compare the overall mean crime rate that you get to the national rate reported in the NCVS reports. They should be in the same ball park.
2. OK. As long as everything looks nice in PDF I wouldn't stress it.

**Comment by jmshapir** [comment]
@gbreynol what is the consensus about whether we are meeting this coming MOnday?

**Comment by gbreynol** [comment]
There are a couple of senior weeks events in the afternoon, so we were wondering if we could change the meeting time to the morning? Maybe 10:00 or 11:00?

**Comment by jmshapir** [comment]
I could do a short meeting at 11:30--would that work?

**Comment by lilyhoffman17** [comment]
That works for me .

**Comment by gbreynol** [comment]
Perfect!
