### ISSUE TITLE
Draft question

### ISSUE THREAD

**Issue by lilyhoffman17** [tinoreskovic/Mass-Media-Independent-Research#29]
Hi @jmshapir , 

I have a question about my draft. I am redoing the paper to model the previous one, but instead of years of broadcasting I have months of broadcasting so it is more granular (and it already looks much better). I only have collected data though early 1927, which means my only observed presidential election year with treated counties is 1924. I have redone all of the descriptive graphs, made new ones + added in more professional, new regression results tables. I also have updated the data section, made edits to the background section, and am working on updating the methods section. I will also add in a brief results section with the data thus far.

My two main questions are:
(1) for the time lag regressions with months, do you think it would ok to create the indicator variables from a range? Example: 1 year post radio entry roughly being ~3 - 12 months after licensing, 2 year post radio entry roughly being 13-24 months post licensing? 
(2) Do you think it makes sense to write an entire discussion section given that my results may change as I finish adding in the new data? (I am a little burnt out and probably won't be able to finish this by the end of today)

Thanks! 
Lily

**Comment by lilyhoffman17** [comment]
I will continue to make edits tomorrow- I have made a master list at the beginning of the paper of progress + questions, as well as comments that I am still incorporating fully. 

https://docs.google.com/document/d/1mE2vNAbDbWOoxGLOSnY3Pl0oBzl1sGGmhot6hHLXwIE/edit#

**Comment by jmshapir** [comment]
@lilyhoffman17 to your questions:
1. That sounds reasonable to me. I can look at it in more detail once it's in place.
2. I think writing a brief discussion section is a good idea. You can flesh it out more later once the results are in place.

**Comment by jmshapir** [comment]
@lilyhoffman17 which sections or components do you think it is most useful for me to comment on at this point? I know some are still to change as new data come in, and some I have reviewed already.

**Comment by jmshapir** [comment]
@lilyhoffman17 just checking in re: the above. Is there a portion of the draft that I can usefully review at this point?

**Comment by lilyhoffman17** [comment]
Hi @jmshapir , I am making a few final edits to the section, but the data section is ready for review! 
Thanks

**Comment by jmshapir** [comment]
Great, thanks @lilyhoffman17. I made a number of comments and suggested edits there. For the bigger picture things I think maybe it makes sense to circle back once you've filled in the rest of the new analysis. Once you have the new data and have some analysis you feel you can trust maybe we can meet to discuss.

**Comment by lilyhoffman17** [comment]
Thanks for the comments! I will continue to work on the paper, incorporate comments, and finalize the dataset over the next few weeks. (I will be back in Prov on June 15) I will let you know when I have the right data and analysis that I feel comfortable with. Thanks-

**Comment by jmshapir** [comment]
Thanks @lilyhoffman17. Why don't you get in touch by e-mail so we can schedule a time to meet after you are back in town.

-Jesse

**Comment by lilyhoffman17** [comment]
Sounds good
